name: Sphinx build and deploy documentation

on:
  push:
    branches:
      - main

jobs:
  build-documentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/workflows/prepare-hatch.yml
      with:
        python-version: 3.8
    - name: Build HTML
      run: python -m hatch run docs:build
    - name: Get version
      id: versioning
      run: |
        t=$(python -m hatch version)
        echo "VERSION=${t%.*}.x" >> $GITHUB_OUTPUT
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: html-docs
        path: docs/build/html/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        destination_dir: ${{ steps.versioning.outputs.VERSION}}
        publish_dir: docs/build/html
