name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prepare-environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  test:
    needs: prepare-environment
    strategy:
      matrix:
        # Run in all these versions of Python
        python-version: [3.8, 3.9]

    steps:
        # Setup which version of Python to use
      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
        # Display the Python version being used
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install requisites
        run: |
          python -m pip install --upgrade pip hatch        

      - name: Run tests
        run: hatch run test.py${{ matrix.python-version }}:no-cov

  documentation-coverage:
    needs: prepare-environment
    steps:
    
    - name: Set Up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install requisites
      run: python -m pip install --upgrade pip
    - name: Install hatch
      run: python  -m pip install hatch
    - name: check test coverage
      run: python -m hatch run docs:cov
        
  changelog-enforcer:
    needs: prepare-environment
    steps:
    - uses: dangoslen/changelog-enforcer@v3
      with:
        changeLogPath: './Changelog.md'

  check-linted:
    needs: prepare-environment
    steps:
      - uses: actions/setup-python@v3
      - uses: psf/black@stable
        with:
          src: "./src"
