name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  do-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:        
        python-version: [3.8, 3.9]
    uses: ./.github/workflows/prepare-hatch.yml
    with:
      python-version: ${{ matrix.python-version }}

    steps:
        # Checkout the latest code from the repo
      - name: Checkout repo
        uses: actions/checkout@v2
        # Display the Python version being used
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Run tests
        run: hatch run test.py${{ matrix.python-version }}:cov
